% Bing sandbox

app_id = '243C9AAF515AE3EE49D775D19F5F8F3F0F0A3D84';
query = 'Tower%20Bridge';
num = '25';

request_url = ['http://api.bing.net/json.aspx?' ...
               'AppId=' app_id ...
               '&Query=' query ...
               '&Sources=Image' ...
               '&Version=2.0' ...
               '&Adult=Strict' ...
               '&Image.Count=' num ...
               '&Image.Filters=Style:Photo+Size:Large' ...
               '&JsonType=raw' ...
              ];
          
fprintf([request_url '\n']);

response = urlread(request_url);

resp = parse_json(response);

num_results = length(resp{1}.SearchResponse.Image.Results);
resp{1}.SearchResponse.Image.Results{1}.MediaUrl